name: Generate Nuget package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal      
      
    - name: Add GPR Source using nuget.exe
      run: |
        nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/Aarklendoia/index.json" -UserName Aarklendoia -Password ${{ secrets.GHPackagesToken }}
        nuget pack
        nuget push "Aark.SecurityHeaders.Extension.nupkg" -Source "GitHub"
      
    - name: Push Github Package
      run: nuget push Aark.SecurityHeaders.Extension\**\*.nupkg -source "GitHub" -SkipDuplicate
      
    - name: Add NuGet API key
      run: nuget setapikey ${{ secrets.NugetAarkSecurityHeadersExtension }}
      
    - name: Push NuGet Gallery
      run: nuget push Aark.SecurityHeaders.Extension\**\*.nupkg -source https://api.nuget.org/v3/index.json -SkipDuplicate
