name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet and create prerelease nupkg
      run: dotnet build --configuration Release
      shell: bash
    - name: Publish nuget to GitHub Packages
      run: |
           for f in ./Aark.SecurityHeaders.Extension/bin/Release/*.nupkg
           do
             curl -vX PUT -u "Aarklendoia:${{ secrets.GHPackagesToken }}" -F package=@$f https://nuget.pkg.github.com/Aarklendoia/
           done
      shell: bash
      
